package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestWildcardCertsRoundTrip(t *testing.T) {
	c := &proxyConfig{mainFolder: t.TempDir()}

	if got := c.loadWildcardCerts(); got != nil {
		t.Fatalf("expected nil before any registration, got %v", got)
	}

	if err := c.registerWildcardCert("lnln.eu", "lnln.eu-wildcard"); err != nil {
		t.Fatal(err)
	}
	if err := c.registerWildcardCert("nunissum.eu", "nunissum.eu-wildcard"); err != nil {
		t.Fatal(err)
	}
	// Registering the same cert name again must not duplicate the entry.
	if err := c.registerWildcardCert("lnln.eu", "lnln.eu-wildcard"); err != nil {
		t.Fatal(err)
	}

	got := c.loadWildcardCerts()
	if len(got) != 2 {
		t.Fatalf("expected 2 entries, got %d: %+v", len(got), got)
	}
	byDomain := map[string]string{}
	for _, w := range got {
		byDomain[w.Domain] = w.Cert
	}
	if byDomain["lnln.eu"] != "lnln.eu-wildcard" || byDomain["nunissum.eu"] != "nunissum.eu-wildcard" {
		t.Errorf("unexpected contents: %+v", got)
	}
}

func TestCertSitesIncludesWildcards(t *testing.T) {
	dir := t.TempDir()
	cfgFile := filepath.Join(dir, "sites.conf")
	if err := os.WriteFile(cfgFile, []byte("==lnln.eu <-w>\napi 10.0.0.1:8080\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	c := &proxyConfig{mainFolder: dir, configFile: cfgFile}
	if err := c.registerWildcardCert("lnln.eu", "lnln.eu-wildcard"); err != nil {
		t.Fatal(err)
	}

	sites := c.certSites()
	var found *certSite
	for i := range sites {
		if sites[i].certName == "lnln.eu-wildcard" {
			found = &sites[i]
		}
	}
	if found == nil {
		t.Fatalf("expected a wildcard cert job among certSites(), got %+v", sites)
	}
	want := []string{"lnln.eu", "*.lnln.eu"}
	if len(found.sans) != 2 || found.sans[0] != want[0] || found.sans[1] != want[1] {
		t.Errorf("sans = %v, want %v", found.sans, want)
	}
}

const sampleManconfSiteBlock = `############
# a.lnln.eu
# autogenerated using >> cmnds revpro
# DON'T EDIT DIRECTLY, revpro OVERWRITES THIS FILE!!!
############
server {
    listen 443 ssl;
    server_name a.lnln.eu www.a.lnln.eu;

    ssl_certificate /revpro/certs/a.lnln.eu/a.lnln.eu.crt;
    ssl_certificate_key /revpro/certs/a.lnln.eu/a.lnln.eu.key;
    ssl_trusted_certificate /revpro/certs/a.lnln.eu/a.lnln.eu.issuer.crt;
}
`

func TestManconfCertSitesParsesRevproShapedFile(t *testing.T) {
	dir := t.TempDir()
	manDir := filepath.Join(dir, "manconf")
	if err := os.MkdirAll(manDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(manDir, "a.lnln.eu.conf"), []byte(sampleManconfSiteBlock), 0o644); err != nil {
		t.Fatal(err)
	}
	c := &proxyConfig{mainFolder: dir}

	sites := c.manconfCertSites()
	if len(sites) != 1 {
		t.Fatalf("expected 1 cert site, got %+v", sites)
	}
	if sites[0].certName != "a.lnln.eu" {
		t.Errorf("certName = %q", sites[0].certName)
	}
	want := []string{"a.lnln.eu", "www.a.lnln.eu"}
	if len(sites[0].sans) != 2 || sites[0].sans[0] != want[0] || sites[0].sans[1] != want[1] {
		t.Errorf("sans = %v, want %v", sites[0].sans, want)
	}
}

func TestManconfCertSitesSkipsUnrecognizedShape(t *testing.T) {
	dir := t.TempDir()
	manDir := filepath.Join(dir, "manconf")
	if err := os.MkdirAll(manDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// A hand-written file with no ssl_certificate directive at all.
	if err := os.WriteFile(filepath.Join(manDir, "custom.conf"), []byte("server {\n    listen 8080;\n    server_name custom.lnln.eu;\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	c := &proxyConfig{mainFolder: dir}
	if sites := c.manconfCertSites(); len(sites) != 0 {
		t.Errorf("expected no cert sites for an unrecognized shape, got %+v", sites)
	}
}

func TestCertSitesIncludesManconfSites(t *testing.T) {
	dir := t.TempDir()
	cfgFile := filepath.Join(dir, "sites.conf")
	if err := os.WriteFile(cfgFile, []byte("==lnln.eu <-w>\napi 10.0.0.1:8080\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	manDir := filepath.Join(dir, "manconf")
	if err := os.MkdirAll(manDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(manDir, "a.lnln.eu.conf"), []byte(sampleManconfSiteBlock), 0o644); err != nil {
		t.Fatal(err)
	}
	c := &proxyConfig{mainFolder: dir, configFile: cfgFile}

	sites := c.certSites()
	names := map[string]bool{}
	for _, s := range sites {
		names[s.certName] = true
	}
	if !names["api.lnln.eu"] {
		t.Errorf("expected the sites.conf cert job to still be present: %+v", sites)
	}
	if !names["a.lnln.eu"] {
		t.Errorf("expected the manconf cert job to be included: %+v", sites)
	}
}

func TestCertSitesSitesConfTakesPrecedenceOverManconf(t *testing.T) {
	dir := t.TempDir()
	cfgFile := filepath.Join(dir, "sites.conf")
	// The same cert name ("a.lnln.eu") is already covered by sites.conf.
	if err := os.WriteFile(cfgFile, []byte(`==lnln.eu <-w>
a 10.0.0.1:8080 --cert="a.lnln.eu"
`), 0o644); err != nil {
		t.Fatal(err)
	}
	manDir := filepath.Join(dir, "manconf")
	if err := os.MkdirAll(manDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(manDir, "stale.conf"), []byte(sampleManconfSiteBlock), 0o644); err != nil {
		t.Fatal(err)
	}
	c := &proxyConfig{mainFolder: dir, configFile: cfgFile}

	sites := c.certSites()
	count := 0
	for _, s := range sites {
		if s.certName == "a.lnln.eu" {
			count++
		}
	}
	if count != 1 {
		t.Errorf("expected exactly one cert job for a.lnln.eu (sites.conf wins), got %d: %+v", count, sites)
	}
}
